# Generated by Django 3.0.8 on 2020-07-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200711_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Mysubscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='coment',
            field=models.CharField(default='1', max_length=128),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='1', max_length=128),
        ),
    ]
