# Generated by Django 3.0.8 on 2020-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200716_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='coment',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
