# Generated by Django 3.1.1 on 2020-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productinbasket_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='creted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
