# Generated by Django 3.1.1 on 2020-10-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200930_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='nub',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
