# Generated by Django 3.1.1 on 2020-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201001_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='nub',
            field=models.IntegerField(default=1),
        ),
    ]
