# Generated by Django 3.1.1 on 2020-10-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201005_1112'),
        ('orders', '0012_auto_20201005_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product'),
        ),
    ]
