# Generated by Django 3.1.1 on 2020-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20201005_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='nub',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
